/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DocsLayoutRouteImport } from './routes/_docs-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsLayoutDocsSplatRouteImport } from './routes/_docs-layout/docs.$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLayoutRoute = DocsLayoutRouteImport.update({
  id: '/_docs-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLayoutDocsSplatRoute = DocsLayoutDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => DocsLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs/$': typeof DocsLayoutDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs/$': typeof DocsLayoutDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docs-layout': typeof DocsLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/_docs-layout/docs/$': typeof DocsLayoutDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/docs/$'
  id: '__root__' | '/' | '/_docs-layout' | '/about' | '/_docs-layout/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsLayoutRoute: typeof DocsLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs-layout': {
      id: '/_docs-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DocsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs-layout/docs/$': {
      id: '/_docs-layout/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsLayoutDocsSplatRouteImport
      parentRoute: typeof DocsLayoutRoute
    }
  }
}

interface DocsLayoutRouteChildren {
  DocsLayoutDocsSplatRoute: typeof DocsLayoutDocsSplatRoute
}

const DocsLayoutRouteChildren: DocsLayoutRouteChildren = {
  DocsLayoutDocsSplatRoute: DocsLayoutDocsSplatRoute,
}

const DocsLayoutRouteWithChildren = DocsLayoutRoute._addFileChildren(
  DocsLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsLayoutRoute: DocsLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
